# Generated by Django 2.2.11 on 2020-03-12 10:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, unique=True)),
                ('tableau', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('dt', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('entete', models.CharField(max_length=12, unique=True)),
                ('grains', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('couverture', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('timezone', models.CharField(max_length=40)),
                ('regle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produit.Regle')),
            ],
        ),
        migrations.CreateModel(
            name='Cdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reseau', models.DateTimeField()),
                ('reception', models.DateTimeField()),
                ('seuils_grains', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('seuils_troncons', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('retard', models.BooleanField(default=False)),
                ('statut_carto', models.BooleanField(default=False)),
                ('statut_etats', models.BooleanField(default=False)),
                ('statut_avertissements', models.BooleanField(default=False)),
                ('statut_diffusions', models.BooleanField(default=False)),
                ('statut_acquitements', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produit.Produit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cdp',
            constraint=models.UniqueConstraint(fields=('produit', 'reseau'), name='unique_reseau_par_produit'),
        ),
    ]
