# Image Docker avec mfserv
image: registry.gitlab.meteo.fr:80/metwork-plugins/docker_build/mfserv-gitlab-ci:2.4

# Base PostgreSQL pour les tests unitaires Django
# Host: postgres, port 5432
services:
  - postgres:latest

# Étapes du pipeline
stages:
  - unittests
  - sonar
  - build

# Variables pour la base PostgreSQL
variables:
  POSTGRES_DB: plugin_apicvf_base
  POSTGRES_USER: metwork
  POSTGRES_PASSWORD: metwork

# Avant script
.before_script_template: &prepare-env
  before_script:
    - cp gitlab-ci-script.sh /usr/local/bin/
    - chmod +x /usr/local/bin/gitlab-ci-script.sh
    - su - mfserv

# Lance tests unitaires + coverage + sonar
# Scanne le code et envoi sur http://sonar.meteo.fr/dashboard?id=apic%3Acarto
unit-testing:
  stage: unittests
  <<: *prepare-env
  script:
    - echo 'Launch unittests + coverage + Sonar'
    - su -c "gitlab-ci-script.sh --testu_sonar" - mfserv

# Build .plugin
build-artifacts:
  stage: build
  <<: *prepare-env
  script:
    - echo 'Build plugin'
    - su -c "gitlab-ci-script.sh --build" - mfserv
    