# Generated by Django 2.2.9 on 2020-02-11 13:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdpApicFr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type2cdp', models.CharField(choices=[('APIC', 1), ('VF', 2)], max_length=4)),
                ('produit', models.CharField(default='AFR', max_length=3)),
                ('name', models.CharField(max_length=80)),
                ('dt', models.DateTimeField()),
                ('grains', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'verbose_name': 'Cdp pour les Apic métropole',
                'verbose_name_plural': 'CDP APIC METROs',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=6, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('cheflieu', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=6, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('cheflieu', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('tableau', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('dt', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AFR', 'APIC METROPOLE'), ('VFR', 'VF METROPOLE'), ('AAG', 'APIC ANTILLES GUYANE'), ('AOI', 'APIC OCEAN INDIEN'), ('ANC', 'APIC NOUVELLE CALEDONIE')], default='AFR', max_length=3, unique=True)),
                ('regle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procedere.Regle')),
            ],
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=6, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('arr', models.CharField(max_length=4, null=True)),
                ('cp', models.CharField(max_length=6, null=True)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='procedere.Dept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat_reg_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat_grain_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('grain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Grain')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat_dept_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Dept')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dept',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedere.Region'),
        ),
    ]
