cd # Generated by Django 2.2.10 on 2020-02-27 14:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=6, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('cheflieu', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=6, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('cheflieu', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, unique=True)),
                ('tableau', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('dt', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('entete', models.CharField(max_length=12, unique=True)),
                ('grains', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('couverture', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('timezone', models.CharField(max_length=40)),
                ('regle', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Regle')),
            ],
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=6, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('arr', models.CharField(max_length=4, null=True)),
                ('cp', models.CharField(max_length=6, null=True)),
                ('dept', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.PROTECT, to='procedere.Dept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtatRegionProduit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('reseau', models.DateTimeField(null=True)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('produit', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
                ('reg', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtatProduit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('reseau', models.DateTimeField(null=True)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('produit', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtatGrainProduit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('reseau', models.DateTimeField(null=True)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('grain', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Grain')),
                ('produit', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtatDeptProduit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('reseau', models.DateTimeField(null=True)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('dept', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Dept')),
                ('produit', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dept',
            name='region',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='procedere.Region'),
        ),
        migrations.CreateModel(
            name='Cdp',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('reseau', models.DateTimeField()),
                ('reception', models.DateTimeField()),
                ('seuils_grains',
                 django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('seuils_troncons', django.contrib.postgres.fields.jsonb.JSONField(
                    default=dict, null=True)),
                ('retard', models.BooleanField(default=False)),
                ('statut_carto', models.BooleanField(default=False)),
                ('statut_etats', models.BooleanField(default=False)),
                ('statut_avertissements', models.BooleanField(default=False)),
                ('statut_diffusions', models.BooleanField(default=False)),
                ('statut_acquitements', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='procedere.Produit')),
            ],
        ),
    ]
