# Generated by Django 2.2.9 on 2020-02-13 16:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau', models.DateTimeField()),
                ('reception', models.DateTimeField()),
                ('grains', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('retard', models.BooleanField(default=False)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CdpApicFr',
        ),
        migrations.AddField(
            model_name='produit',
            name='entete',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='regle',
            name='dt',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cdp',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procedere.Produit'),
        ),
    ]
