# Generated by Django 2.2.9 on 2020-01-29 15:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprise_reg_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('emprise_dept_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('emprise_grain_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('derniere_alerte', models.DateTimeField(null=True)),
                ('derniere_alerte_ensemble', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('derniere_alerte_seuil', models.SmallIntegerField(default=0)),
                ('souscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=2, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('cheflieu', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AFR', 'APIC METROPOLE'), ('VFR', 'VF METROPOLE'), ('AAG', 'APIC ANTILLES GUYANE'), ('AOI', 'APIC OCEAN INDIEN'), ('ANC', 'APIC NOUVELLE CALEDONIE')], default='AFR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=2, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('cheflieu', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('derniere_alerte', models.DateTimeField(null=True)),
                ('derniere_alerte_ensemble', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('derniere_alerte_seuil', models.SmallIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=2, unique=True)),
                ('tncc', models.SmallIntegerField(null=True)),
                ('ncc', models.CharField(max_length=200, null=True)),
                ('nccenr', models.CharField(max_length=200, null=True)),
                ('libelle', models.CharField(max_length=200, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('arr', models.CharField(max_length=4, null=True)),
                ('cp', models.CharField(max_length=6, null=True)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apicvf.Dept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat_grain_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('grain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Grain')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat_dept_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Dept')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dept',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Region'),
        ),
    ]
