# Generated by Django 2.2.9 on 2020-01-22 09:07

import apicvf.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprise_nat', models.BooleanField(default=False)),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=2)),
                ('metrop', models.BooleanField(default=True)),
                ('cheflieu', models.CharField(max_length=5)),
                ('tncc', models.SmallIntegerField()),
                ('ncc', models.CharField(max_length=100)),
                ('nccenr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'APIC'), ('V', 'VF')], default='V', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=7, unique=True)),
                ('cp', models.CharField(max_length=6, null=True)),
                ('reg', models.CharField(max_length=8, null=True)),
                ('metrop', models.BooleanField(default=True)),
                ('tncc', models.SmallIntegerField(default=0)),
                ('ncc', models.CharField(default='', max_length=100)),
                ('nccenr', models.CharField(default='', max_length=100)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apicvf.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='EtatGrainProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('alerte_time', models.DateTimeField(null=True)),
                ('aboList', models.TextField(default='')),
                ('aboArray', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('grain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Grain')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='EtatDeptProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('alerte_time', models.DateTimeField(null=True)),
                ('alerte_emp', django.contrib.postgres.fields.jsonb.JSONField(default=apicvf.models.default_emp, null=True)),
                ('aboList', models.TextField(default='')),
                ('aboArray', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Dept')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Avertissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dts', models.DateTimeField()),
                ('seuil', models.SmallIntegerField()),
                ('abo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Abonnement')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apicvf.Dept')),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='emprise_dept',
            field=models.ManyToManyField(blank=True, db_table='emprise_dept', null=True, to='apicvf.EtatDeptProduit'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='emprise_grain',
            field=models.ManyToManyField(blank=True, db_table='emprise_grain', null=True, to='apicvf.EtatGrainProduit'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit'),
        ),
    ]
