# Generated by Django 2.2.9 on 2020-01-22 10:36

import apicvf.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicvf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat_dept_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('alerte_time', models.DateTimeField(null=True)),
                ('alerte_emp', django.contrib.postgres.fields.jsonb.JSONField(default=apicvf.models.default_emp, null=True)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Etat_grain_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('alerte_time', models.DateTimeField(null=True)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('grain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Grain')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='etatgrainproduit',
            name='grain',
        ),
        migrations.RemoveField(
            model_name='etatgrainproduit',
            name='produit',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='emprise_dept_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='emprise_grain_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='emprise_dept',
            field=models.ManyToManyField(blank=True, db_table='emprise_dept', to='apicvf.Etat_dept_produit'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='emprise_grain',
            field=models.ManyToManyField(blank=True, db_table='emprise_grain', to='apicvf.Etat_grain_produit'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Region'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(choices=[('AFR', 'APIC METROPOLE'), ('VFR', 'VF METROPOLE'), ('AAG', 'APIC ANTILLES GUYANE'), ('AOI', 'APIC OCEAN INDIEN'), ('ANC', 'APIC NOUVELLE CALEDONIE')], default='AFR', max_length=10),
        ),
        migrations.DeleteModel(
            name='EtatDeptProduit',
        ),
        migrations.DeleteModel(
            name='EtatGrainProduit',
        ),
        migrations.AddField(
            model_name='etat_grain_produit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit'),
        ),
        migrations.AddField(
            model_name='etat_dept_produit',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Dept'),
        ),
        migrations.AddField(
            model_name='etat_dept_produit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit'),
        ),
    ]
