# Generated by Django 2.2.9 on 2020-01-22 14:33

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicvf', '0002_auto_20200122_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etat_dept_produit',
            old_name='alerte_time',
            new_name='derniere_alerte',
        ),
        migrations.RenameField(
            model_name='etat_grain_produit',
            old_name='alerte_time',
            new_name='derniere_alerte',
        ),
        migrations.RemoveField(
            model_name='avertissement',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='cheflieu',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='ncc',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='nccenr',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='tncc',
        ),
        migrations.RemoveField(
            model_name='etat_dept_produit',
            name='alerte_emp',
        ),
        migrations.RemoveField(
            model_name='grain',
            name='ncc',
        ),
        migrations.RemoveField(
            model_name='grain',
            name='nccenr',
        ),
        migrations.RemoveField(
            model_name='grain',
            name='reg',
        ),
        migrations.RemoveField(
            model_name='grain',
            name='tncc',
        ),
        migrations.AddField(
            model_name='avertissement',
            name='emprise_alerte',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='libelle',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dept',
            name='nom',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etat_dept_produit',
            name='derniere_alerte_grains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grain',
            name='libelle',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grain',
            name='nom',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grain',
            name='insee',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
