# Generated by Django 2.2.9 on 2020-02-03 15:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicvf', '0002_auto_20200129_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_2', models.SmallIntegerField(default=0)),
                ('t_1', models.SmallIntegerField(default=0)),
                ('t0', models.SmallIntegerField(default=0)),
                ('abo_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Souscription',
        ),
    ]
