# Generated by Django 2.2.9 on 2020-02-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicvf', '0003_auto_20200203_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='souscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apicvf.Etat_produit'),
        ),
    ]
