# Generated by Django 2.2.9 on 2020-01-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicvf', '0003_auto_20200122_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='grain',
            name='nom',
        ),
        migrations.AddField(
            model_name='dept',
            name='cheflieu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='ncc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='nccenr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='tncc',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='arr',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='ncc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='nccenr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='tncc',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='cheflieu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='libelle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='metrop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='ncc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='nccenr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='tncc',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='insee',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='libelle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grain',
            name='libelle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='insee',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
