# Generated by Django 2.2.9 on 2020-01-22 09:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apicvf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriCdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('seuil', models.SmallIntegerField()),
                ('grain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apicvf.Grain', to_field='insee')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apicvf.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='CdpApic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(default='apic', max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('dt', models.DateTimeField()),
                ('grains', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdp.BatchCdp', to_field='name')),
            ],
            options={
                'verbose_name': 'Cdp pour les Apic métropole',
                'verbose_name_plural': 'CDP APIC METROs',
            },
        ),
        migrations.AddConstraint(
            model_name='historicdp',
            constraint=models.UniqueConstraint(fields=('produit', 'ts', 'grain'), name='1grain_1prod_1temps'),
        ),
    ]
