# Generated by Django 2.2.9 on 2020-01-29 15:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CdpApic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(default='AFR', max_length=3)),
                ('name', models.CharField(max_length=80)),
                ('dt', models.DateTimeField()),
                ('grains', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdp.BatchCdp', to_field='name')),
            ],
            options={
                'verbose_name': 'Cdp pour les Apic métropole',
                'verbose_name_plural': 'CDP APIC METROs',
            },
        ),
    ]
